// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhittyServer.Web.Data;

namespace WhittyServer.Web.Migrations
{
    [DbContext(typeof(WhittyGittersDbContext))]
    [Migration("20180925184102_seeder")]
    partial class seeder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WhittyServer.Web.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<double>("Highscore");

                    b.Property<string>("Image");

                    b.Property<string>("IngameName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new { Id = new Guid("ed596935-fb00-486b-ba11-727270cdfa62"), Email = "jens@whittygitters.be", FirstName = "Jens", Highscore = 0.0, IngameName = "TheFirstOfTheWhittens", LastName = "De Weirdt", Password = "thaha" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
